name: artifact

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: compress
        run: |
          7z a -tzip a.zip ./src/**
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: a.zip