name: Multi

on:
  workflow_dispatch:

  push:

permissions:
  contents: write

jobs:
  release:
    name: release
    if: startsWith(github.ref, 'refs/tags/')    
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: compress
        run: |
          7z a -tzip a.zip ./src/**
      
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: a.zip
  
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: compress
        run: |
          7z a -tzip a.zip ./src/**

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: a.zip