name: release

on:
  push:
    
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: compress
        if: startsWith(github.ref, 'refs/tags/')    
        run: |
          7z a -tzip a.zip ./src/**
      
      - name: release
        if: startsWith(github.ref, 'refs/tags/')    
        uses: softprops/action-gh-release@v2
        with:
          files: a.zip