name: release from artifact

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: release
    if: startsWith(github.ref, 'refs/tags/')    
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
      
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/myimage.tar
  